version: '3'
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        restart: always
        volumes:
            - ./public:/var/www/html
            - ./etc/nginx/logs/:/var/log/nginx/
            - ./etc/nginx/sites-enabled/:/etc/nginx/conf.d/
        depends_on:
            - php
            - mariadb
    php:
        image: bitnami/php-fpm
        container_name: php
        expose:
            - "9000"
        restart: always
        volumes:
            - ./public:/var/www/html
    mariadb:
        image: mariadb:latest
        container_name: mariadb
        ports:
            - "3306:3306"
        restart: always
        volumes:
            - ./data/mariadb:/var/lib/mariadb
        environment:
            MYSQL_ROOT_PASSWORD: root
    phpmyadmin:
        image: phpmyadmin:latest
        container_name: phpmyadmin
        ports:
            - "8080:80"
        restart: always
        depends_on:
            - mariadb
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: mariadb